#!/bin/bash

# check if the directory was provided
if [ -z "$1" ]; then
	echo "Usage: log-archive <log-directory>"
	exit 1
fi

LOG_DIR="$1"

#check if directory exits
if [ ! -d "$LOG_DIR" ]; then
	echo "Error: Directory '$LOG_DIR' does not exist!"
	exit 1
fi

#output directory for archives
ARCHIVE_DIR="/var/log_archives"
mkdir -p "$ARCHIVE_DIR"

#create timestamp
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

#output file name
ARCHIVE_FILE="$ARCHIVE_DIR/logs_archive_${TIMESTAMP}.tar.gz"

#compress logs
tar -czf "$ARCHIVE_FILE" "$LOG_DIR"

#log the activity
echo "[$(date)] Archived $LOG_DIR to $ARCHIVE_FILE" >> "$ARCHIVE_DIR/archive.log"

echo "Archive completed succefully!"
echo "created: $ARCHIVE_FILE"


